项目代码/shiwoxinyi/UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace UI.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        ManagerManager ma = new ManagerManager();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login([Bind(Include = "ManagerName,ManagerPass")]string ManagerName, string ManagerPass)
        {
            try
            {
                var users = ma.Denglu(ManagerName, ManagerPass);
                if (users != null)
                {
                    //保存到Session HttpContext.
                    Session["Manager_id"] = ManagerName;
                    //string data = "登录成功";
                    return Content("<script>;alert('登录成功！');window.location.href='/ManagerAdd/menu';</script>");
                }
                else
                {
                    //string data = "登录失败";
                    return Content("<script>;alert('登录失败！');window.history.go(-1);</script>");
                }
            }
            catch (Exception ex)
            {
                string data = "错误";
                return Content("<script>;alert('登录失败！');window.history.go(-1);</script>");
            }
        }
    }
}

项目代码/shiwoxinyi/UI/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;
using System.Net;
using PagedList;
using System.IO;
using System.Web.Helpers;

namespace UI.Controllers
{
    public class GoodsController : Controller
    {
        // GET: Goods
        shiwoxinyigaiEntities db = new shiwoxinyigaiEntities();
        GoodsManager goodsmanager = new GoodsManager();

        #region 商品列表
        public ActionResult Index(int? page)
        {
            var goods = goodsmanager.GetGoods();
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(goods.ToPagedList(pageNumber,pageSize));
        }
        #endregion

        #region 添加商品
        #region //添加商品的Get方法
        public ActionResult GoodsCreate()
        {
            //存储在ViewBag.CategoryId属性中的分类数据是为了让视图中的DropDownList辅助方法检索
            //SelectList类用于表示构建下拉列表需要的数据，构造函数的第1个参数指定了将要放在列表中的项，
            //第2个参数是一个属性名称，该属性包含当用户选择一个指定项时使用的键值，
            //第3个参数是每一项要显示的文本，第4个参数包含了最初选定项的值。
            ViewBag.GoodsK_id = new SelectList(db.GoodsK, "GoodsK_id", "GoodsKName");
            return View("GoodsCreate");

        }
        #endregion
        // POST: StoreManager/Create
        #region//添加商品的POST方法
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        //[ValidateAntiForgeryToken]特性用来防止伪造的跨站请求，配合表单中的@Html.AntiForgeryToken()使用
        //对数据进行增删改时要防止csrf攻击！
        //该特性表示检测服务器请求是否被篡改。注意：该特性只能用于post请求，get请求无效。
        //public ActionResult GoodsCreate([Bind(Include = "Goods_id,GoodsName,GoodsImage,GoodsJianjie,GoodsDetails,AddTime,Price,Count,GoodsK_id")]Goods goods)
        public ActionResult GoodsCreate([Bind(Include = "Goods_id,GoodsName,GoodsImage,GoodsJianjie,GoodsDetails,AddTime,Price,Count,GoodsK_id")]Goods goods)
        {


            try
            {
                HttpPostedFileBase postimage1 = Request.Files["GoodsImage"];

                string filePath = postimage1.FileName;
                string filename = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                string serverpath = Server.MapPath(@"\Images\goods\") + filename;
                string relativepath = @"/Images/goods/" + filename;
                postimage1.SaveAs(serverpath);
                goods.GoodsImage = relativepath;

                goods.AddTime = System.DateTime.Now;
                goodsmanager.AddGoods(goods);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            ViewBag.GoodsK_id = new SelectList(db.GoodsK, "GoodsK_id", "GoodsKName", goods.GoodsK_id);
            return View("GoodsCreate", goods);
        }
        #endregion

        #endregion

        #region 更新商品
        #region //更新商品的Get方法
        public ActionResult GoodsEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goods goods = goodsmanager.GetGoodsById(id);
            if (goods == null)
            {
                return HttpNotFound();
            }

            ViewBag.GoodsK_id = new SelectList(db.GoodsK, "GoodsK_id", "GoodsKName", goods.GoodsK_id);
            return View(goods);
        }
        #endregion
        //POST:StoreManager/Edit/5

        #region //编辑商品的POST方法
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        //[ValidateAntiForgeryToken]特性用来防止伪造的跨站请求，配合表单中的@Html.AntiForgeryToken()使用
        //对数据进行增删改时要防止csrf攻击！
        //该特性表示检测服务器请求是否被篡改。注意：该特性只能用于post请求，get请求无效。
        public ActionResult GoodsEdit(Goods goods)
        {
            //[Bind(Include = "Goods_id,GoodsName,GoodsImage,GoodsJianjie,GoodsDetails,AddTime,Price,Count,GoodsK_id")] 
            //使用Bind属性的目的是限制用户在提交form表单时使用合适且正确的值。当我们提交一个表单时，就会检查每一个实体上绑定的特性。
            //Bind属性是一个重要的安全机制，可以防止黑客攻击。
            if (ModelState.IsValid)
            {
                HttpPostedFileBase postimage1 = Request.Files["GoodsImage"];
                if (postimage1 != null)
                {
                    string filePath = postimage1.FileName;
                    string filename = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                    string serverpath = Server.MapPath(@"\Images\goods\") + filename;
                    string relativepath = @"/Images/goods/" + filename;
                    postimage1.SaveAs(serverpath);
                    goods.GoodsImage = relativepath;
                }
                db.SaveChanges();
                goodsmanager.EditGoods(goods);
                return RedirectToAction("Index");
            }
            ViewBag.GoodsK_id = new SelectList(db.GoodsK, "GoodsK_id", "GoodsKName", goods.GoodsK_id);
            return View(goods);
        }
        #endregion
        //删除给定的id的商品
        #endregion

        #region 删除商品
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goods book = db.Goods.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }
        // POST: StoreManager/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[ValidateAntiForgeryToken]特性用来防止伪造的跨站请求，配合表单中的@Html.AntiForgeryToken()使用
        //对数据进行增删改时要防止csrf攻击！
        //该特性表示检测服务器请求是否被篡改。注意：该特性只能用于post请求，get请求无效。
        public ActionResult DeleteConfiremed(int id)
        {
            Goods book = db.Goods.Find(id);
            db.Goods.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goods book = db.Goods.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }
        #endregion

        #region 新娘饰品商品详情页
        public ActionResult GoodsDetails(int Goods_id)
        {
            Session["Goods_id"] = Goods_id;
            if (Session["Goods_id"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var goodses = goodsmanager.GetGoodsById(Goods_id);
            if (goodses == null)
            {
                return HttpNotFound();
            }
            return View(goodses);
        }
        #endregion
    }
}

项目代码/shiwoxinyi/UI/Views/Shared/HouTai.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/Images/Home/shiwoxinyilogo.ico" type="image/x-icon" />

    <link title="" href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <link title="blue" href="~/Content/css/dermadefault.css" rel="stylesheet" type="text/css" />
    <link title="green" href="~/Content/css/dermagreen.css" rel="stylesheet" type="text/css" disabled="diaabled" />
    <link title="orange" href="~/Content/css/dermaorange.css" rel="stylesheet" disabled="disable" />
    <link href="~/Content/css/templatecss.css" rel="stylesheet" title="" type="text/css" />
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.cookie.js" type="text/javascript"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/ckeditor/config.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <style type="text/css">
        .content {
            margin-bottom: 40px;
            margin-top: 20px;
            margin-left: 50px;
        }

        .title_top {
            margin-top: 20px;
            background-color: #dd3b64;
            padding: 5px;
            border-radius: 2px;
            background-position: -88px 0pt;
            color: #FFFFFF;
            width: 100%;
        }

        .div {
            margin-top: 30px;
        }

        .aaa {
            width: 100%;
            height: 200px;
        }
    </style>
    @RenderSection("style", required: false)
</head>
<body>
    <nav class="nav navbar-default navbar-mystyle navbar-fixed-top" style="background-color: #0087b4;color: #fff;">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand mystyle-brand" href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-home" style="color: #fff;"></span></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="li-border"><a class="mystyle-color" href="#" style="color: #fff;">饰我心意  后台</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right">

                <li class="dropdown li-border">
                    @if (Session["Users_id"] != null)
                    {
                        <a href="#" class="dropdown-toggle mystyle-color" data-toggle="dropdown">@Session["ManagerName"]<span class="caret"></span></a>
                    }
                    else
                    {
                        <a href="#" class="dropdown-toggle mystyle-color" data-toggle="dropdown" style="color: #fff;">饰我心意<span class="caret"></span></a>
                    }
                    <ul class="dropdown-menu">
                        <li><a href="">退出</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle mystyle-color" data-toggle="dropdown" style="color: #fff;">换肤<span class="caret"></span></a>
                    <ul class="dropdown-menu changecolor">
                        <li id="blue"><a href="#">蓝色</a></li>
                        <li class="divider"></li>
                        <li id="green"><a href="#">绿色</a></li>
                        <li class="divider"></li>
                        <li id="orange"><a href="#">橙色</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div class="down-main">
        <div class="left-main left-full">
            <div class="sidebar-fold"><span class="glyphicon glyphicon-align-justify"></span></div>
            <div class="subNavBox">
                <div class="sBox">
                    <div class="subNav sublist-down">
                        <span class="title-icon glyphicon glyphicon-compressed"></span><span class="sublist-title">添加管理</span>
                    </div>
                    <ul class="navContent" style="display:none">                        
                        <li>
                            <div class="showtitle" style="width:100px;"><img src="~/Manager/img/leftimg.png" />商品添加</div>
                            <a href="@Url.Action("GoodsCreate","Goods")"><span class="sublist-icon glyphicon glyphicon-plus"></span><span class="sub-title">商品添加</span></a>
                        </li>                        
                    </ul>
                </div>
                <div class="sBox">
                    <div class="subNav sublist-up"><span class="title-icon glyphicon glyphicon-chevron-up"></span><span class="sublist-title">列表管理</span></div>
                    <ul class="navContent" style="display:none">                        
                        <li>
                            <div class="showtitle" style="width:100px;"><img src="~/Manager/img/leftimg.png" />商品列表</div>
                            <a href="@Url.Action("Index","Goods")"><span class="sublist-icon glyphicon glyphicon-envelope"></span><span class="sub-title">商品列表</span></a>
                        </li>
                        <li>
                            <div class="showtitle" style="width:100px;"><img src="~/Manager/img/leftimg.png" />订单列表</div>
                            <a href="@Url.Action("OrdersIndex","Mall")"><span class="sublist-icon glyphicon glyphicon-envelope"></span><span class="sub-title">订单列表</span></a>
                        </li>                                               
                    </ul>
                </div>
            </div>
        </div>
        <div class="right-product view-product right-off">
            <div class="container-fluid">
                <div class="info-center">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            /*换肤*/
            $(".dropdown .changecolor li").click(function () {
                var style = $(this).attr("id");
                $("link[title!='']").attr("disabled", "disabled");
                $("link[title='" + style + "']").removeAttr("disabled");

                $.cookie('mystyle', style, { expires: 7 }); // 存储一个带7天期限的 cookie
            })
            var cookie_style = $.cookie("mystyle");
            if (cookie_style != null) {
                $("link[title!='']").attr("disabled", "disabled");
                $("link[title='" + cookie_style + "']").removeAttr("disabled");
            }
            /*左侧导航栏显示隐藏功能*/
            $(".subNav").click(function () {
                /*显示*/
                if ($(this).find("span:first-child").attr('class') == "title-icon glyphicon glyphicon-chevron-down") {
                    $(this).find("span:first-child").removeClass("glyphicon-chevron-down");
                    $(this).find("span:first-child").addClass("glyphicon-chevron-up");
                    $(this).removeClass("sublist-down");
                    $(this).addClass("sublist-up");
                }
                /*隐藏*/
                else {
                    $(this).find("span:first-child").removeClass("glyphicon-chevron-up");
                    $(this).find("span:first-child").addClass("glyphicon-chevron-down");
                    $(this).removeClass("sublist-up");
                    $(this).addClass("sublist-down");
                }
                // 修改数字控制速度， slideUp(500)控制卷起速度
                $(this).next(".navContent").slideToggle(300).siblings(".navContent").slideUp(300);
            })
            /*左侧导航栏缩进功能*/
            $(".left-main .sidebar-fold").click(function () {

                if ($(this).parent().attr('class') == "left-main left-full") {
                    $(this).parent().removeClass("left-full");
                    $(this).parent().addClass("left-off");

                    $(this).parent().parent().find(".right-product").removeClass("right-full");
                    $(this).parent().parent().find(".right-product").addClass("right-off");

                }
                else {
                    $(this).parent().removeClass("left-off");
                    $(this).parent().addClass("left-full");

                    $(this).parent().parent().find(".right-product").removeClass("right-off");
                    $(this).parent().parent().find(".right-product").addClass("right-full");

                }
            })

            /*左侧鼠标移入提示功能*/
            $(".sBox ul li").mouseenter(function () {
                if ($(this).find("span:last-child").css("display") == "none") { $(this).find("div").show(); }
            }).mouseleave(function () { $(this).find("div").hide(); })
        })
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

项目代码/shiwoxinyi/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Images/Home/shiwoxinyilogo.ico" type="image/x-icon" />
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/HeadFoot.css" rel="stylesheet" />
    @RenderSection("style", required: false)
    
</head>
<body>
    <header>
        <div class="bignav" style="display: block;">
            <div class="container1">
                <div class="bignav_left bignav_same">
                    <ul style="position: relative;">
                        @if (Session["Users_id"] != null)
                        {
                            <li class="usercenterbox" style="display: none;"><a href="@Url.Action("Shopcar","Mall",new {Users_id = @Session["Users_id"]})"><span class="iconfont usercenter"> &#xe640;</span></a></li>
                            <li class="zhuxiaobox" style="display: none;"><span class="iconfont zhuxiao">&#xe610;</span></li>
                            <li class="userinfobox" style="margin-left: 0px;"><span class="iconfont userinfo" aria-hidden="true"><a href="@Url.Action("UserCenter","UserInfo",new {Users_id = @Session["Users_id"]})"><img class="userinfo sessionimage" src="@Session["UserImage"]" /></a></span></li>
                        }
                        else
                        {
                            <li class="userinfobox userinfobox1" style="margin-left: 0px; color: rgba(57, 33, 11, 1); cursor: pointer;"><span class="iconfont userinfo" aria-hidden="true">&#xe62b;</span></li>
                        }
                    </ul>
                </div>
                <div class="bignav_center">
                    <a href="@Url.Action("Index","Home")"><img src="~/Images/Home/shiwoxinyilogo.png" width="200" height="40" style="margin-top: 16px;margin-left: -36px;" /></a>
                </div>
                <div class="bignav_right bignav_same">
                    <ul>
                        <li><a href="@Url.Action("Index","Mall")">商城</a></li>
                        <li style="margin-right: 0px;"><a href="javascript:void(0)" class="nav_search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="smallnav" style="display: none;">
            <div class="container">
                <div class="smallnav_logo">
                    <a><img src="~/Images/Home/shiwoxinyilogo.png" width="40" height="40" /></a>
                </div>
                <button type="button" class="open open1">-</button>
                <button type="button" class="open open2" style="display: none;">×</button>
                <ul style="display: none;">
                    <li style="margin-top: 10px;"><a href="javascript:void(0)">登陆/注册</a></li>
                    <li><a href="javascript:void(0)">商城</a></li>
                </ul>
            </div>
        </div>
    </header>
    <!--搜索-->
    <div class="search" style="display: none;">
        <div class="closed close" style="cursor: pointer;font-size: 30px;text-align: center;line-height: 30px;color: white; background-color: #DD3B44; width: 30px; height: 30px; -webkit-border-radius: 30px; float: right; margin-top: 10px; margin-right: 20px; ">×</div>
        <form>
            <input type="search" class="input_search" value="" placeholder="请输入搜索内容...." required />
            <div type="submit" class="btn btn_search">搜索</div>
        </form>
    </div>

    <div id="denglubox" class="denglubox" style="display: none;background: url(../../Content/../Images/RegisterLogin/dengluzhuce.jpg) left center repeat-x;">
        <div class="closed" style="cursor: pointer;font-size: 30px;text-align: center;line-height: 30px;color: white; background-color: #DD3B44; width: 30px; height: 30px; -webkit-border-radius: 30px; float: right; margin-top: 10px; margin-right: 20px; ">×</div>
        <div class="zuo" style="width: 30%;height: 100%;float: right;margin-right:90px; margin-top: 100px;">
            <div class="mengban" style="width: 400px;height: 400px;padding-top:0px;overflow: visible;background-color: rgba(1, 1, 1, 0.2);">
                <div class="formheader" style="width: 100%;font-size: 18px; padding-top: 30px;margin: 10px auto;text-align: center;">
                    <label id="hlkNormalLogin" style="color: #E5E5E5;">用户登录</label>
                </div>
                <div class="normalInput normaluser">
                    <input id="Users_id" placeholder="用户名" value="" style="height: 46px;width: 80%; float: left;" maxlength="32" />
                    <div class="usertip"></div>
                </div>
                <div class="normalInput normalpassword">
                    <input id="UserPass" placeholder="密码" style="height: 46px;width: 80%;float: left;" maxlength="20" type="password" value="" />
                    <span class="iconfont showpassword" style="display: none; font-size: 40px;float: left;margin-left: 200px;margin-top: -50px;">&#xe80b;</span>
                    <span class="iconfont hidepassword" style="display: block; color:rgba(178,178,178,1);font-size: 48px;margin-left: 200px;float: left;margin-top: -55px;">&#xe6a2;</span>
                    <div class="passtip"></div>
                </div>
                <input id="dl" type="submit" value="登录" class="cssbtnRegister" style="margin-left: 52px;color: white; font-size: 14px; background-color: #32A5E7; height: 46px; width: 300px;" />
                <a href="@Url.Action("Register","UserInfo")"><label class="ljzc">立即注册</label></a>
                <br />
            </div>
        </div>
    </div>
    @RenderBody()
    <!--回到顶部-->
    <div id="toTop"><img src="~/Images/Home/totop.png" /></div>
    <!--底部-->
    <footer>
        <div class="container">
            <div class="row">
                <article class="footleft">
                    <div class="foot_part1 foot_part col-lg-3">
                        <ul>
                            <li class="foot_part_title">网站功能</li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">商品浏览</a></li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">商品购买</a></li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">论坛原创</a></li>
                        </ul>
                    </div>
                    <div class="foot_part2 foot_part col-lg-3">
                        <ul>
                            <li class="foot_part_title">成长之路</li>
                            <li class="foot_part_choose"><a href="http://219.229.243.64/NSYY/">霓裳羽衣</a></li>
                            <li class="foot_part_choose"><a href="http://219.229.243.64/Association/">+社团</a></li>
                            <li class="foot_part_choose"><a href="http://219.229.243.64/pinpai/">品牌网</a></li>
                        </ul>
                    </div>
                    <div class="foot_part1 foot_part col-lg-3">
                        <ul>
                            <li class="foot_part_title">友情链接</li>
                            <li class="foot_part_choose"><a href="http://www.jxnu.edu.cn/">江西师大</a></li>
                            <li class="foot_part_choose"><a href="http://http://www.mobanwang.com/">模板王</a></li>
                            <li class="foot_part_choose"><a href="http://www.sucaihuo.com/">素材火</a></li>
                        </ul>
                    </div>
                    <div class="foot_part2 foot_part col-lg-3">
                        <ul>
                            <li class="foot_part_title">关于我们</li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">免责声明</a></li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">联系我们</a></li>
                            <li class="foot_part_choose"><a href="javascript:void(0)">意见反馈</a></li>
                        </ul>
                    </div>
                </article>
            </div>
            @*<div class="col-md-4 col-sm-6 col-xs-12">
                    <article class="footright">

                    </article>
                </div>*@
        </div>
        <div class="contactus">
            <span class="p">关注我们：</span>
            <a href="javascript:void(0)"><span class="iconfont weixin">&#xe6bb;</span></a>
            <a href="javascript:void(0)"><span class="iconfont weibo">&#xe6c0;</span></a>
            <a href="javascript:void(0)"><span class="iconfont tenxun">&#xe6b9;</span></a>
            <a href="javascript:void(0)"><span class="iconfont qqkongjian">&#xe693;</span></a>
        </div>
        <div class="foot-bottom">
            <ul>
                <li>管理员信箱：1229150012@qq.com</li>
                <li>地址：江西省南昌市瑶湖江西师范大学</li>
                <li><a class="foot-bottom-3" href="@Url.Action("Login","Admin")">后台入口</a></li>
                <li><br />版权所有&nbsp;&copy;江西师范大学软件学院</li>
            </ul>
        </div>
    </footer><!--底部部分 结束-->
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
   
    <script src="~/Scripts/jquery.validate.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/JS/HeadFoot.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>